FROM eclipse-temurin:17-jdk AS builder

WORKDIR /sources
COPY ./gradle /sources/gradle
COPY ./gradlew /sources
COPY ./Havana-Server/ /sources/Havana-Server
COPY ./Havana-Web/ /sources/Havana-Web
COPY ./settings.gradle /sources

RUN ./gradlew :Havana-Web:shadowJar

FROM eclipse-temurin:17-jre
WORKDIR /havana-web

# Copy the JAR file from build
COPY --from=builder /sources/Havana-Web/build/libs/Havana-Web-unspecified.jar /havana-web/Havana-Web.jar

# Copy figuredata.xml
COPY ./tools/figuredata.xml /havana-web/

# Copy entrypoint script
COPY ./tools/docker/web-entrypoint.sh /havana-web/run.sh
RUN chmod +x /havana-web/run.sh

ENTRYPOINT ["/havana-web/run.sh"]
