FROM eclipse-temurin:17-jdk AS builder

WORKDIR /sources
COPY ./gradle /sources/gradle
COPY ./gradlew /sources
COPY ./Havana-Server/ /sources/Havana-Server
COPY ./build.gradle /sources
COPY ./settings.gradle /sources

# Ensure clean state for build
RUN rm -rf /sources/Havana-Server/build
RUN sed -i -e 's/\r$//' ./gradlew && chmod +x ./gradlew
RUN ./gradlew :Havana-Server:clean :Havana-Server:shadowJar

FROM eclipse-temurin:17-jre
WORKDIR /havana-server

# Copy the JAR file from build
COPY --from=builder /sources/Havana-Server/build/libs/Havana-Server-unspecified.jar /havana-server/Havana-Server.jar

# Copy figuredata.xml
COPY ./tools/figuredata.xml /havana-server/

# Copy entrypoint script
COPY ./tools/docker/server-entrypoint.sh /havana-server/run.sh
RUN sed -i -e 's/\r$//' /havana-server/run.sh && chmod +x /havana-server/run.sh

ENTRYPOINT ["/havana-server/run.sh"]
