FROM eclipse-temurin:17-jdk AS builder

WORKDIR /sources
COPY . /sources

RUN ./gradlew build
RUN cd Havana-Server/build/distributions && tar xf Havana-Server.tar
RUN cd Havana-Server/build/distributions/Havana-Server/bin && ./Havana-Server

FROM eclipse-temurin:17-jre
COPY --from=builder /sources/Havana-Server/build/distributions/Havana-Server /havana-server
COPY --from=builder /sources/figuredata.xml /havana-server/bin
COPY --from=builder /sources/tools/docker/server-entrypoint.sh /havana-server/bin/run.sh
WORKDIR /havana-server/bin
RUN chmod +x run.sh
ENTRYPOINT ["/havana-server/bin/run.sh"]
