name: Create Pre-Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  pre-release:
    permissions: write-all
    
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build distribution with Gradle
        run: ./gradlew distZip
        
      - name: File release preparation
        run: |
          sudo mkdir ./Havana
          sudo mkdir ./Havana/lib
          sudo mkdir ./Havana/tools
          sudo mv ./Havana-Server/build/Havana-Server-unspecified.jar ./Havana/Havana-Server.jar
          sudo mv ./Havana-Server/build/Havana-Web-unspecified.jar ./Havana/Havana-Web.jar
          sudo cp tools/scripts/run_server.bat ./Havana/
          sudo cp tools/scripts/run_server.sh ./Havana/
          sudo cp tools/scripts/run_web.bat ./Havana/
          sudo cp tools/scripts/run_web.sh ./Havana/
          sudo cp tools/havana.sql ./Havana/
          sudo cp tools/figuredata.xml ./Havana/
          sudo mkdir ./Havana/tools/www
          sudo mkdir ./Havana/tools/www-tpl
          sudo mv tools/www-tpl/* ./Havana/tools/www-tpl/
          sudo cp tools/scripts/README.txt ./Havana/

      - id: get-tag
        name: Get tag version
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Compress release files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./Havana-${{ steps.get-tag.outputs.tag }}.zip ./Havana
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.get-tag.outputs.tag }}"
          prerelease: true
          title: "Pre-release ${{ steps.get-tag.outputs.tag }}"
          files: |
            Havana-${{ steps.get-tag.outputs.tag }}.zip
