name: Create Pre-Release

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    permissions: write-all
    
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew fatJar
      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
      - name: Rename server jar file
        run: cp Havana-Server/build/libs/Havana-Server-all.jar Havana-Server-${{ steps.sha-short.outputs.sha-short }}.jar
      - name: Rename web jar file
        run: cp Havana-Web/build/libs/Havana-Web-all.jar Havana-Web-${{ steps.sha-short.outputs.sha-short }}.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.sha-short.outputs.sha-short }}"
          files: |
            Havana-Server-${{ steps.sha-short.outputs.sha-short }}.jar
            Havana-Web-${{ steps.sha-short.outputs.sha-short }}.jar