name: Create Pre-Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  pre-release:
    permissions: write-all
    
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Build distribution with Gradle
        run: ./gradlew distZip
        
      - name: Decompress web distribution file
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq Havana-Web/build/distributions/Havana-Web.zip -d ./release
          
      - name: Decompress server distribution file
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq Havana-Server/build/distributions/Havana-Server.zip -d ./release
          
      - name: File release preparation
        run: |
          sudo rm -rf ./release/Havana-Web/bin/*
          sudo rm -rf ./release/Havana-Web/bin
          sudo rm -rf ./release/Havana-Server/bin/*
          sudo rm -rf ./release/Havana-Server/bin
          sudo mkdir ./Havana
          sudo mkdir ./Havana/lib
          sudo mkdir ./Havana/tools
          sudo mv ./release/Havana-Web/lib/Havana-Server.jar ./Havana/Havana-Server.jar
          sudo mv ./release/Havana-Web/lib/Havana-Web.jar ./Havana/Havana-Web.jar
          sudo mv ./release/Havana-Web/lib/* ./Havana/lib
          sudo mv ./release/Havana-Server/lib/* ./Havana/lib
          sudo cp tools/scripts/run_server.bat ./Havana/
          sudo cp tools/scripts/run_server.sh ./Havana/
          sudo cp tools/scripts/run_web.bat ./Havana/
          sudo cp tools/scripts/run_web.sh ./Havana/
          sudo cp tools/havana.sql ./Havana/
          sudo cp tools/figuredata.xml ./Havana/
          sudo mkdir ./Havana/tools/www
          sudo mkdir ./Havana/tools/www-tpl
          sudo mv tools/www-tpl/* ./Havana/tools/www-tpl/
          sudo cp tools/scripts/README.txt ./Havana/

      - id: sha-short
        name: Get short SHA
        run: echo "::set-output name=sha-short::$(git rev-parse --short HEAD)"
        
      - name: Compress release files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./Havana-${{ steps.sha-short.outputs.sha-short }}.zip ./Havana
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ steps.sha-short.outputs.sha-short }}"
          files: |
            Havana-${{ steps.sha-short.outputs.sha-short }}.zip
